import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'fr' | 'en' | 'es' | 'zh' | 'ja';

interface Translations {
  [key: string]: {
    [lang in Language]: string;
  };
}

const translations: Translations = {
  // Sidebar
  'install_app': { fr: 'Installer l\'App', en: 'Install App', es: 'Instalar App', zh: '安装应用', ja: 'アプリをインストール' },
  'dashboard': { fr: 'Tableau de bord', en: 'Dashboard', es: 'Panel', zh: '仪表板', ja: 'ダッシュボード' },
  'student_dashboard': { fr: 'Tableau de bord Élève', en: 'Student Dashboard', es: 'Panel de Estudiante', zh: '学生仪表板', ja: '学生ダッシュボード' },
  'student_card': { fr: 'Carte Utilisateur', en: 'User Card', es: 'Tarjeta de Usuario', zh: '用户卡', ja: 'ユーザーカード' },
  'classroom': { fr: 'Espace Classe', en: 'Classroom', es: 'Aula', zh: '教室', ja: '教室' },
  'newsfeed': { fr: 'Histoire', en: 'News Feed', es: 'Noticias', zh: '动态', ja: 'ニュースフィード' },
  'directory': { fr: 'Répertoire', en: 'Directory', es: 'Directorio', zh: '目录', ja: 'ディレクトリ' },
  'messaging': { fr: 'Messagerie', en: 'Messaging', es: 'Mensajería', zh: '消息', ja: 'メッセージング' },
  'classroom_subtitle_teacher': { fr: 'Gérez le comportement et partagez des ressources', en: 'Manage behavior and share resources', es: 'Gestionar el comportamiento y compartir recursos', zh: '管理行为并共享资源', ja: '行動を管理し、リソースを共有する' },
  'classroom_subtitle_student': { fr: 'Vos ressources et points de comportement', en: 'Your resources and behavior points', es: 'Tus recursos y puntos de comportamiento', zh: '您的资源和行为点数', ja: 'あなたのリソースと行動ポイント' },
  'no_class_assigned': { fr: 'Vous n\'avez aucune classe assignée.', en: 'You have no class assigned.', es: 'No tienes ninguna clase asignada.', zh: '您没有分配任何班级。', ja: 'クラスが割り当てられていません。' },
  'students_behavior': { fr: 'Élèves & Comportement', en: 'Students & Behavior', es: 'Estudiantes y Comportamiento', zh: '学生与行为', ja: '学生と行動' },
  'my_behavior_points': { fr: 'Mes Points de Comportement', en: 'My Behavior Points', es: 'Mis Puntos de Comportamiento', zh: '我的行为点数', ja: '私の行動ポイント' },
  'behavior_points_added': { fr: 'Points de comportement', en: 'Behavior Points', es: 'Puntos de comportamiento', zh: '行为点数', ja: '行動ポイント' },
  'behavior_warning': { fr: 'Avertissement de comportement', en: 'Behavior Warning', es: 'Advertencia de comportamiento', zh: '行为警告', ja: '行動警告' },
  'no_student_in_class': { fr: 'Aucun élève dans cette classe.', en: 'No student in this class.', es: 'Ningún estudiante en esta clase.', zh: '该班级没有学生。', ja: 'このクラスには学生がいません。' },
  'total_points': { fr: 'Total des points', en: 'Total points', es: 'Puntos totales', zh: '总分', ja: '合計ポイント' },
  'history': { fr: 'Historique', en: 'History', es: 'Historial', zh: '历史', ja: '履歴' },
  'no_points_recorded': { fr: 'Aucun point enregistré.', en: 'No points recorded.', es: 'No hay puntos registrados.', zh: '没有记录点数。', ja: 'ポイントは記録されていません。' },
  'resources': { fr: 'Ressources', en: 'Resources', es: 'Recursos', zh: '资源', ja: 'リソース' },
  'no_resources_shared': { fr: 'Aucune ressource partagée pour le moment.', en: 'No resources shared yet.', es: 'Aún no se han compartido recursos.', zh: '尚未共享资源。', ja: 'まだリソースは共有されていません。' },
  'evaluate': { fr: 'Évaluer', en: 'Evaluate', es: 'Evaluar', zh: '评估', ja: '評価する' },
  'positive': { fr: 'Positif', en: 'Positive', es: 'Positivo', zh: '积极', ja: 'ポジティブ' },
  'needs_improvement': { fr: 'À améliorer', en: 'Needs improvement', es: 'Necesita mejorar', zh: '需要改进', ja: '改善が必要' },
  'number_of_points': { fr: 'Nombre de points', en: 'Number of points', es: 'Número de puntos', zh: '点数', ja: 'ポイント数' },
  'reason_comment': { fr: 'Raison / Commentaire', en: 'Reason / Comment', es: 'Razón / Comentario', zh: '原因/评论', ja: '理由/コメント' },
  'reason_placeholder': { fr: 'Ex: Bonne participation, Travail non fait...', en: 'Ex: Good participation, Homework not done...', es: 'Ej: Buena participación, Tarea no hecha...', zh: '例如：积极参与，未完成作业...', ja: '例：積極的な参加、宿題未提出...' },
  'share_resource': { fr: 'Partager une ressource', en: 'Share a resource', es: 'Compartir un recurso', zh: '共享资源', ja: 'リソースを共有する' },
  'resource_type': { fr: 'Type de ressource', en: 'Resource type', es: 'Tipo de recurso', zh: '资源类型', ja: 'リソースタイプ' },
  'document_pdf_word': { fr: 'Document (PDF, Word...)', en: 'Document (PDF, Word...)', es: 'Documento (PDF, Word...)', zh: '文档（PDF，Word...）', ja: 'ドキュメント（PDF、Word...）' },
  'image_photo': { fr: 'Image / Photo', en: 'Image / Photo', es: 'Imagen / Foto', zh: '图片 / 照片', ja: '画像 / 写真' },
  'publish_to': { fr: 'Publier dans :', en: 'Publish to:', es: 'Publicar en:', zh: '发布到：', ja: '公開先：' },
  'class_story': { fr: 'Histoire de classe & Ressources', en: 'Class Story & Resources', es: 'Historia de la clase y recursos', zh: '班级故事和资源', ja: 'クラスストーリーとリソース' },
  'file_upload': { fr: 'Fichier (PDF, Word, etc.)', en: 'File (PDF, Word, etc.)', es: 'Archivo (PDF, Word, etc.)', zh: '文件（PDF，Word等）', ja: 'ファイル（PDF、Wordなど）' },
  'web_link': { fr: 'Lien Web', en: 'Web Link', es: 'Enlace web', zh: '网页链接', ja: 'Webリンク' },
  'video': { fr: 'Vidéo', en: 'Video', es: 'Video', zh: '视频', ja: 'ビデオ' },
  'title': { fr: 'Titre', en: 'Title', es: 'Título', zh: '标题', ja: 'タイトル' },
  'title_placeholder': { fr: 'Ex: Chapitre 1 - Les fractions', en: 'Ex: Chapter 1 - Fractions', es: 'Ej: Capítulo 1 - Fracciones', zh: '例如：第1章 - 分数', ja: '例：第1章 - 分数' },
  'url_link': { fr: 'URL / Lien', en: 'URL / Link', es: 'URL / Enlace', zh: 'URL / 链接', ja: 'URL / リンク' },
  'description_optional': { fr: 'Description (optionnelle)', en: 'Description (optional)', es: 'Descripción (opcional)', zh: '描述（可选）', ja: '説明（オプション）' },
  'description_placeholder': { fr: 'Instructions pour les élèves...', en: 'Instructions for students...', es: 'Instrucciones para los estudiantes...', zh: '学生须知...', ja: '学生への指示...' },
  'sharing': { fr: 'Partage...', en: 'Sharing...', es: 'Compartiendo...', zh: '分享中...', ja: '共有中...' },
  'share': { fr: 'Partager', en: 'Share', es: 'Compartir', zh: '分享', ja: '共有する' },
  'leaderboard': { fr: 'Classement', en: 'Leaderboard', es: 'Clasificación', zh: '排行榜', ja: 'リーダーボード' },
  'recent_connections': { fr: 'Connexions', en: 'Connections', es: 'Conexiones', zh: '连接', ja: '接続' },
  'users': { fr: 'Utilisateurs', en: 'Users', es: 'Usuarios', zh: '用户', ja: 'ユーザー' },
  'attendance': { fr: 'Présences', en: 'Attendance', es: 'Asistencia', zh: '出勤', ja: '出席' },
  'reports': { fr: 'Rapports', en: 'Reports', es: 'Informes', zh: '报告', ja: 'レポート' },
  'classes': { fr: 'Classes', en: 'Classes', es: 'Clases', zh: '班级', ja: 'クラス' },
  'settings': { fr: 'Paramètres', en: 'Settings', es: 'Ajustes', zh: '设置', ja: '設定' },
  'scanner': { fr: 'Scanner Admin', en: 'Admin Scanner', es: 'Escáner Admin', zh: '管理员扫描仪', ja: '管理者スキャナー' },
  'mobile_app': { fr: 'App Mobile (Test)', en: 'Mobile App (Test)', es: 'App Móvil (Prueba)', zh: '移动应用 (测试)', ja: 'モバイルアプリ (テスト)' },
  'kiosk': { fr: 'Mode Borne', en: 'Kiosk Mode', es: 'Modo Quiosco', zh: '自助终端模式', ja: 'キオスクモード' },
  'houses': { fr: 'Maisons', en: 'Houses', es: 'Casas', zh: '学院', ja: 'ハウス' },
  'integration': { fr: 'Architecture', en: 'Architecture', es: 'Arquitectura', zh: '架构', ja: 'アーキテクチャ' },
  'profile': { fr: 'Mon Profil', en: 'My Profile', es: 'Mi Perfil', zh: '我的个人资料', ja: 'マイプロフィール' },
  'logout': { fr: 'Déconnexion', en: 'Logout', es: 'Cerrar sesión', zh: '登出', ja: 'ログアウト' },
  
  // Header
  'search_placeholder': { fr: 'Rechercher un élève, un professeur...', en: 'Search for a student, a teacher...', es: 'Buscar un estudiante, un profesor...', zh: '搜索学生，老师...', ja: '学生、先生を検索...' },
  'notifications': { fr: 'Notifications', en: 'Notifications', es: 'Notificaciones', zh: '通知', ja: '通知' },
  'mark_all_read': { fr: 'Tout marquer comme lu', en: 'Mark all as read', es: 'Marcar todo como leído', zh: '全部标记为已读', ja: 'すべて既読にする' },
  'no_notifications': { fr: 'Aucune notification', en: 'No notifications', es: 'Sin notificaciones', zh: '没有通知', ja: '通知なし' },

  // Roles & Statuses (Data)
  'role_admin': { fr: 'Administrateur', en: 'Administrator', es: 'Administrador', zh: '管理员', ja: '管理者' },
  'role_enseignant': { fr: 'Enseignant', en: 'Teacher', es: 'Profesor', zh: '教师', ja: '先生' },
  'role_élève': { fr: 'Élève', en: 'Student', es: 'Estudiante', zh: '学生', ja: '学生' },
  'role_personnel administratif': { fr: 'Personnel', en: 'Staff', es: 'Personal', zh: '员工', ja: 'スタッフ' },
  'status_Présent': { fr: 'Présent', en: 'Present', es: 'Presente', zh: '出勤', ja: '出席' },
  'status_Retard': { fr: 'Retard', en: 'Late', es: 'Tarde', zh: '迟到', ja: '遅刻' },
  'status_Absent': { fr: 'Absent', en: 'Absent', es: 'Ausente', zh: '缺席', ja: '欠席' },

  // Days
  'day_Lun': { fr: 'Lun', en: 'Mon', es: 'Lun', zh: '周一', ja: '月' },
  'day_Mar': { fr: 'Mar', en: 'Tue', es: 'Mar', zh: '周二', ja: '火' },
  'day_Mer': { fr: 'Mer', en: 'Wed', es: 'Mié', zh: '周三', ja: '水' },
  'day_Jeu': { fr: 'Jeu', en: 'Thu', es: 'Jue', zh: '周四', ja: '木' },
  'day_Ven': { fr: 'Ven', en: 'Fri', es: 'Vie', zh: '周五', ja: '金' },

  // Dashboard
  'overview_attendance_today': { fr: 'Aperçu des présences d\'aujourd\'hui', en: 'Overview of today\'s attendance', es: 'Resumen de la asistencia de hoy', zh: '今日出勤概览', ja: '今日の出席の概要' },
  'discipline_alerts_current_week': { fr: 'Alertes de Discipline (Semaine en cours)', en: 'Discipline Alerts (Current Week)', es: 'Alertas de Disciplina (Semana Actual)', zh: '纪律警报（本周）', ja: '規律アラート（今週）' },
  'action_required': { fr: 'Action requise', en: 'Action required', es: 'Acción requerida', zh: '需要采取行动', ja: '必要なアクション' },
  'no_data_available': { fr: 'Aucune donnée disponible', en: 'No data available', es: 'No hay datos disponibles', zh: '无可用数据', ja: '利用可能なデータがありません' },
  'presence': { fr: 'Présence', en: 'Presence', es: 'Presencia', zh: '出勤', ja: '出席' },
  'total_students': { fr: 'Total Élèves', en: 'Total Students', es: 'Total de Estudiantes', zh: '学生总数', ja: '総学生数' },
  'present_today': { fr: 'Présents Aujourd\'hui', en: 'Present Today', es: 'Presentes Hoy', zh: '今日出勤', ja: '今日の出席者' },
  'late_today': { fr: 'Retards Aujourd\'hui', en: 'Late Today', es: 'Tardanzas Hoy', zh: '今日迟到', ja: '今日の遅刻者' },
  'absent_today': { fr: 'Absents Aujourd\'hui', en: 'Absent Today', es: 'Ausentes Hoy', zh: '今日缺席', ja: '今日の欠席者' },
  'weekly_attendance': { fr: 'Présence Hebdomadaire', en: 'Weekly Attendance', es: 'Asistencia Semanal', zh: '每周出勤', ja: '週の出席' },
  'recent_activity': { fr: 'Activité Récente', en: 'Recent Activity', es: 'Actividad Reciente', zh: '最近活动', ja: '最近のアクティビティ' },
  'view_all': { fr: 'Voir tout', en: 'View all', es: 'Ver todo', zh: '查看全部', ja: 'すべて表示' },
  'staff': { fr: 'Personnel', en: 'Staff', es: 'Personal', zh: '员工', ja: 'スタッフ' },
  'present': { fr: 'Présent', en: 'Present', es: 'Presente', zh: '出勤', ja: '出席' },
  'late': { fr: 'Retard', en: 'Late', es: 'Tarde', zh: '迟到', ja: '遅刻' },
  'absent': { fr: 'Absent', en: 'Absent', es: 'Ausente', zh: '缺席', ja: '欠席' },

  // MobileApp / Scanner / Kiosk
  'camera_error': { fr: 'Impossible d\'accéder à la caméra.', en: 'Unable to access the camera.', es: 'No se puede acceder a la cámara.', zh: '无法访问相机。', ja: 'カメラにアクセスできません。' },
  'firebase_not_configured': { fr: 'Firebase n\'est pas configuré.', en: 'Firebase is not configured.', es: 'Firebase no está configurado.', zh: '未配置 Firebase。', ja: 'Firebaseが設定されていません。' },
  'account_creation_error': { fr: 'Erreur lors de la création du compte.', en: 'Error creating account.', es: 'Error al crear la cuenta.', zh: '创建帐户时出错。', ja: 'アカウントの作成中にエラーが発生しました。' },
  'biometric_registration_error': { fr: 'Erreur lors de l\'enregistrement biométrique.', en: 'Error during biometric registration.', es: 'Error durante el registro biométrico.', zh: '生物识别注册期间出错。', ja: '生体認証の登録中にエラーが発生しました。' },
  'no_user_biometric_found': { fr: 'Aucun utilisateur avec données biométriques trouvé.', en: 'No user with biometric data found.', es: 'No se encontró ningún usuario con datos biométricos.', zh: '未找到具有生物识别数据的用户。', ja: '生体認証データを持つユーザーが見つかりません。' },
  'recognition_error': { fr: 'Erreur lors de la reconnaissance.', en: 'Error during recognition.', es: 'Error durante el reconocimiento.', zh: '识别期间出错。', ja: '認識中にエラーが発生しました。' },
  'continue_to_biometrics': { fr: 'Continuer vers la biométrie', en: 'Continue to biometrics', es: 'Continuar a biometría', zh: '继续进行生物识别', ja: '生体認証に進む' },
  'account_created_success': { fr: 'Compte créé avec succès', en: 'Account successfully created', es: 'Cuenta creada con éxito', zh: '帐户创建成功', ja: 'アカウントが正常に作成されました' },
  'biometrics_recorded_success': { fr: 'Les données biométriques ont été enregistrées et associées à votre profil.', en: 'Biometric data has been recorded and associated with your profile.', es: 'Los datos biométricos han sido registrados y asociados a su perfil.', zh: '生物识别数据已记录并与您的个人资料关联。', ja: '生体認証データが記録され、プロファイルに関連付けられました。' },
  'step2_biometrics': { fr: 'Étape 2 : Biométrie', en: 'Step 2: Biometrics', es: 'Paso 2: Biometría', zh: '第 2 步：生物识别', ja: 'ステップ 2：生体認証' },
  'biometrics_mandatory_desc': { fr: 'Cette étape est obligatoire pour activer votre compte. Veuillez enregistrer votre visage et votre empreinte.', en: 'This step is mandatory to activate your account. Please register your face and fingerprint.', es: 'Este paso es obligatorio para activar su cuenta. Por favor, registre su rostro y huella dactilar.', zh: '此步骤是激活您的帐户所必需的。请注册您的面部和指纹。', ja: 'この手順はアカウントを有効にするために必須です。顔と指紋を登録してください。' },
  'face_registered': { fr: 'Visage enregistré', en: 'Face registered', es: 'Rostro registrado', zh: '已注册面部', ja: '顔が登録されました' },
  'scan_face': { fr: 'Scanner le visage', en: 'Scan face', es: 'Escanear rostro', zh: '扫描面部', ja: '顔をスキャン' },
  'fingerprint_registered': { fr: 'Empreinte enregistrée', en: 'Fingerprint registered', es: 'Huella dactilar registrada', zh: '已注册指纹', ja: '指紋が登録されました' },
  'scan_fingerprint': { fr: 'Scanner l\'empreinte', en: 'Scan fingerprint', es: 'Escanear huella dactilar', zh: '扫描指纹', ja: '指紋をスキャン' },
  'activate_account': { fr: 'Activer le compte', en: 'Activate account', es: 'Activar cuenta', zh: '激活帐户', ja: 'アカウントを有効にする' },
  'clocking': { fr: 'Pointage', en: 'Clocking', es: 'Fichaje', zh: '打卡', ja: '打刻' },
  'choose_scan_method': { fr: 'Choisissez votre méthode de scan pour enregistrer votre présence.', en: 'Choose your scanning method to record your presence.', es: 'Elija su método de escaneo para registrar su presencia.', zh: '选择您的扫描方法以记录您的出勤。', ja: '出席を記録するためのスキャン方法を選択してください。' },
  'facial_recognition': { fr: 'Reconnaissance Faciale', en: 'Facial Recognition', es: 'Reconocimiento facial', zh: '面部识别', ja: '顔認識' },
  'fingerprint': { fr: 'Empreinte Digitale', en: 'Fingerprint', es: 'Huella dactilar', zh: '指纹', ja: '指紋' },
  'place_finger_on_sensor': { fr: 'Posez votre doigt sur le capteur de l\'appareil', en: 'Place your finger on the device sensor', es: 'Coloque su dedo en el sensor del dispositivo', zh: '将手指放在设备传感器上', ja: 'デバイスのセンサーに指を置いてください' },
  'scanning': { fr: 'Analyse...', en: 'Scanning...', es: 'Escaneando...', zh: '扫描中...', ja: 'スキャン中...' },
  'scan_now': { fr: 'Scanner maintenant', en: 'Scan now', es: 'Escanear ahora', zh: '立即扫描', ja: '今すぐスキャン' },
  'recognized': { fr: 'Reconnu', en: 'Recognized', es: 'Reconocido', zh: '已识别', ja: '認識されました' },
  'user_recognized': { fr: 'Utilisateur reconnu', en: 'User recognized', es: 'Usuario reconocido', zh: '用户已识别', ja: 'ユーザーが認識されました' },
  'presence_recorded_success': { fr: 'Présence enregistrée avec succès', en: 'Presence successfully recorded', es: 'Presencia registrada con éxito', zh: '出勤记录成功', ja: '出席が正常に記録されました' },
  'matricule': { fr: 'Matricule', en: 'Registration Number', es: 'Número de matrícula', zh: '注册号', ja: '登録番号' },
  'time': { fr: 'Heure', en: 'Time', es: 'Hora', zh: '时间', ja: '時間' },
  'status': { fr: 'Statut', en: 'Status', es: 'Estado', zh: '状态', ja: 'ステータス' },
  'finish': { fr: 'Terminer', en: 'Finish', es: 'Terminar', zh: '完成', ja: '終了' },
  'arrival': { fr: 'Arrivée', en: 'Arrival', es: 'Llegada', zh: '到达', ja: '到着' },
  'departure': { fr: 'Départ', en: 'Departure', es: 'Salida', zh: '离开', ja: '出発' },

  // Login
  'fill_required_fields': { fr: 'Veuillez remplir tous les champs obligatoires.', en: 'Please fill in all required fields.', es: 'Por favor, complete todos los campos obligatorios.', zh: '请填写所有必填字段。', ja: 'すべての必須フィールドに入力してください。' },
  'class_required_for_student': { fr: 'La classe est obligatoire pour un élève.', en: 'Class is required for a student.', es: 'La clase es obligatoria para un estudiante.', zh: '学生必须填写班级。', ja: '学生にはクラスが必須です。' },
  'enter_email_password': { fr: 'Veuillez saisir votre email et mot de passe.', en: 'Please enter your email and password.', es: 'Por favor, introduzca su correo electrónico y contraseña.', zh: '请输入您的电子邮件和密码。', ja: 'メールアドレスとパスワードを入力してください。' },
  'email_already_used': { fr: 'Cet email est déjà utilisé par un autre compte.', en: 'This email is already used by another account.', es: 'Este correo electrónico ya está siendo utilizado por otra cuenta.', zh: '此电子邮件已被其他帐户使用。', ja: 'このメールアドレスは別のアカウントで既に使用されています。' },
  'incorrect_email_password': { fr: 'Email ou mot de passe incorrect.', en: 'Incorrect email or password.', es: 'Correo electrónico o contraseña incorrectos.', zh: '电子邮件或密码错误。', ja: 'メールアドレスまたはパスワードが正しくありません。' },
  'password_min_length': { fr: 'Le mot de passe doit contenir au moins 6 caractères.', en: 'Password must be at least 6 characters long.', es: 'La contraseña debe tener al menos 6 caracteres.', zh: '密码必须至少包含 6 个字符。', ja: 'パスワードは6文字以上である必要があります。' },
  'auth_not_enabled': { fr: 'L\'authentification par Email/Mot de passe n\'est pas activée. Veuillez l\'activer dans la console Firebase (Authentication > Sign-in method).', en: 'Email/Password authentication is not enabled. Please enable it in the Firebase console (Authentication > Sign-in method).', es: 'La autenticación por correo electrónico/contraseña no está habilitada. Por favor, actívela en la consola de Firebase (Autenticación > Método de inicio de sesión).', zh: '电子邮件/密码身份验证未启用。请在 Firebase 控制台（身份验证 > 登录方法）中启用它。', ja: 'メールアドレス/パスワード認証が有効になっていません。Firebaseコンソール（Authentication > Sign-in method）で有効にしてください。' },
  'network_error': { fr: 'Erreur de connexion réseau. Veuillez vérifier votre connexion internet ou si un bloqueur de publicités bloque la requête Firebase.', en: 'Network connection error. Please check your internet connection or if an ad blocker is blocking the Firebase request.', es: 'Error de conexión de red. Por favor, compruebe su conexión a Internet o si un bloqueador de anuncios está bloqueando la solicitud de Firebase.', zh: '网络连接错误。请检查您的互联网连接，或者是否有广告拦截器阻止了 Firebase 请求。', ja: 'ネットワーク接続エラー。インターネット接続を確認するか、広告ブロッカーがFirebaseリクエストをブロックしていないか確認してください。' },
  'verifying': { fr: 'Vérification...', en: 'Verifying...', es: 'Verificando...', zh: '验证中...', ja: '確認中...' },
  'continue_step_2': { fr: 'Continuer vers l\'étape 2', en: 'Continue to step 2', es: 'Continuar al paso 2', zh: '继续进行第 2 步', ja: 'ステップ2に進む' },
  'login_button': { fr: 'Se connecter', en: 'Login', es: 'Iniciar sesión', zh: '登录', ja: 'ログイン' },
  'already_have_account': { fr: 'Déjà un compte ? Se connecter', en: 'Already have an account? Login', es: '¿Ya tienes una cuenta? Iniciar sesión', zh: '已有帐户？登录', ja: 'すでにアカウントをお持ちですか？ログイン' },
  'no_account_yet': { fr: 'Pas encore de compte ? Créer un compte', en: 'No account yet? Create an account', es: '¿Aún no tienes cuenta? Crear una cuenta', zh: '还没有帐户？创建一个帐户', ja: 'まだアカウントをお持ちではありませんか？アカウントを作成する' },
  'step1_basic_info': { fr: 'Étape 1 : Informations de base', en: 'Step 1: Basic Information', es: 'Paso 1: Información básica', zh: '第 1 步：基本信息', ja: 'ステップ 1：基本情報' },
  'biometric_registration_follows': { fr: 'L\'enregistrement biométrique suivra à l\'étape 2.', en: 'Biometric registration will follow in step 2.', es: 'El registro biométrico seguirá en el paso 2.', zh: '生物识别注册将在第 2 步中进行。', ja: '生体認証の登録はステップ2で行われます。' },
  'last_name': { fr: 'Nom', en: 'Last Name', es: 'Apellido', zh: '姓氏', ja: '姓' },
  'first_name': { fr: 'Prénom', en: 'First Name', es: 'Nombre', zh: '名字', ja: '名' },
  'role': { fr: 'Rôle', en: 'Role', es: 'Rol', zh: '角色', ja: '役割' },
  'student': { fr: 'Élève', en: 'Student', es: 'Estudiante', zh: '学生', ja: '学生' },
  'teacher': { fr: 'Enseignant', en: 'Teacher', es: 'Profesor', zh: '教师', ja: '教師' },
  'administrative_staff': { fr: 'Personnel Administratif', en: 'Administrative Staff', es: 'Personal administrativo', zh: '行政人员', ja: '事務職員' },
  'admin': { fr: 'Administrateur', en: 'Administrator', es: 'Administrador', zh: '管理员', ja: '管理者' },
  'matricule_optional': { fr: 'Matricule (Optionnel)', en: 'Registration Number (Optional)', es: 'Número de matrícula (Opcional)', zh: '注册号（可选）', ja: '登録番号（任意）' },
  'house_optional': { fr: 'Maison (Optionnel)', en: 'House (Optional)', es: 'Casa (Opcional)', zh: '学院（可选）', ja: 'ハウス（任意）' },
  'no_house': { fr: 'Aucune maison', en: 'No house', es: 'Ninguna casa', zh: '无学院', ja: 'ハウスなし' },

  // Attendance
  'all_statuses': { fr: 'Tous les statuts', en: 'All statuses', es: 'Todos los estados', zh: '所有状态', ja: 'すべてのステータス' },
  'search_by_name': { fr: 'Rechercher par nom...', en: 'Search by name...', es: 'Buscar por nombre...', zh: '按姓名搜索...', ja: '名前で検索...' },
  'no_records_found': { fr: 'Aucun enregistrement trouvé.', en: 'No records found.', es: 'No se encontraron registros.', zh: '未找到记录。', ja: '記録が見つかりません。' },
  'please_configure_firebase': { fr: 'Veuillez configurer Firebase.', en: 'Please configure Firebase.', es: 'Por favor, configure Firebase.', zh: '请配置 Firebase。', ja: 'Firebaseを設定してください。' },
  'confirm': { fr: 'Confirmer', en: 'Confirm', es: 'Confirmar', zh: '确认', ja: '確認' },
  'perfect_attendance': { fr: 'Assiduité parfaite cette semaine. Continuez ainsi !', en: 'Perfect attendance this week. Keep it up!', es: 'Asistencia perfecta esta semana. ¡Sigue así!', zh: '本周出勤完美。继续保持！', ja: '今週は皆勤です。その調子で頑張りましょう！' },
  'attendance_register': { fr: 'Registre des présences', en: 'Attendance Register', es: 'Registro de asistencia', zh: '出勤登记', ja: '出席簿' },
  'view_biometric_history': { fr: 'Consultez l\'historique des pointages biométriques', en: 'View the history of biometric clockings', es: 'Ver el historial de fichajes biométricos', zh: '查看生物识别打卡历史记录', ja: '生体認証の打刻履歴を表示' },
  'export_csv': { fr: 'Exporter CSV', en: 'Export CSV', es: 'Exportar CSV', zh: '导出 CSV', ja: 'CSV エクスポート' },
  'date': { fr: 'Date', en: 'Date', es: 'Fecha', zh: '日期', ja: '日付' },
  'user': { fr: 'Utilisateur', en: 'User', es: 'Usuario', zh: '用户', ja: 'ユーザー' },
  'loading_attendance': { fr: 'Chargement des présences...', en: 'Loading attendance...', es: 'Cargando asistencia...', zh: '正在加载出勤...', ja: '出席を読み込んでいます...' },
  'delete_question': { fr: 'Supprimer ?', en: 'Delete?', es: '¿Eliminar?', zh: '删除？', ja: '削除しますか？' },
  'edit': { fr: 'Modifier', en: 'Edit', es: 'Editar', zh: '编辑', ja: '編集' },
  'delete': { fr: 'Supprimer', en: 'Delete', es: 'Eliminar', zh: '删除', ja: '削除' },
  'cancel': { fr: 'Annuler', en: 'Cancel', es: 'Cancelar', zh: '取消', ja: 'キャンセル' },

  // Users
  'all_roles': { fr: 'Tous les rôles', en: 'All roles', es: 'Todos los roles', zh: '所有角色', ja: 'すべての役割' },
  'email': { fr: 'Email', en: 'Email', es: 'Correo electrónico', zh: '电子邮件', ja: 'メールアドレス' },
  'generate': { fr: 'Générer', en: 'Generate', es: 'Generar', zh: '生成', ja: '生成する' },
  'password': { fr: 'Mot de passe', en: 'Password', es: 'Contraseña', zh: '密码', ja: 'パスワード' },

  // Profile
  'passwords_do_not_match': { fr: 'Les nouveaux mots de passe ne correspondent pas.', en: 'New passwords do not match.', es: 'Las nuevas contraseñas no coinciden.', zh: '新密码不匹配。', ja: '新しいパスワードが一致しません。' },
  'unauthenticated_user': { fr: 'Utilisateur non authentifié.', en: 'Unauthenticated user.', es: 'Usuario no autenticado.', zh: '未经过身份验证的用户。', ja: '認証されていないユーザー。' },
  'password_updated_success': { fr: 'Votre mot de passe a été mis à jour avec succès.', en: 'Your password has been successfully updated.', es: 'Su contraseña ha sido actualizada con éxito.', zh: '您的密码已成功更新。', ja: 'パスワードが正常に更新されました。' },
  'current_password_incorrect': { fr: 'Le mot de passe actuel est incorrect.', en: 'Current password is incorrect.', es: 'La contraseña actual es incorrecta.', zh: '当前密码不正确。', ja: '現在のパスワードが正しくありません。' },
  'too_many_attempts': { fr: 'Trop de tentatives. Veuillez réessayer plus tard.', en: 'Too many attempts. Please try again later.', es: 'Demasiados intentos. Por favor, inténtelo de nuevo más tarde.', zh: '尝试次数过多。请稍后再试。', ja: '試行回数が多すぎます。後でもう一度お試しください。' },
  'error_updating_password': { fr: 'Erreur lors de la mise à jour du mot de passe.', en: 'Error updating password.', es: 'Error al actualizar la contraseña.', zh: '更新密码时出错。', ja: 'パスワードの更新中にエラーが発生しました。' },
  'error_updating_bio': { fr: 'Erreur lors de la mise à jour de la biographie.', en: 'Error updating biography.', es: 'Error al actualizar la biografía.', zh: '更新个人简介时出错。', ja: '自己紹介の更新中にエラーが発生しました。' },
  'tell_us_about_yourself': { fr: 'Parlez-nous un peu de vous...', en: 'Tell us a bit about yourself...', es: 'Cuéntanos un poco sobre ti...', zh: '向我们介绍一下您自己...', ja: 'あなたについて少し教えてください...' },
  'system_admin': { fr: 'Administrateur Système', en: 'System Administrator', es: 'Administrador del Sistema', zh: '系统管理员', ja: 'システム管理者' },
  'admin_desc': { fr: 'En tant qu\'administrateur, vous avez le contrôle total sur la plateforme ShopUniversities. Votre rôle est crucial pour le bon fonctionnement et la sécurité de l\'établissement.', en: 'As an administrator, you have full control over the ShopUniversities platform. Your role is crucial for the proper functioning and security of the establishment.', es: 'Como administrador, tiene control total sobre la plataforma ShopUniversities. Su papel es crucial para el buen funcionamiento y la seguridad del establecimiento.', zh: '作为管理员，您对 ShopUniversities 平台拥有完全控制权。您的角色对于机构的正常运作和安全至关重要。', ja: '管理者として、ShopUniversitiesプラットフォームを完全に制御できます。あなたの役割は、施設の適切な機能とセキュリティにとって重要です。' },
  'admin_task_1': { fr: 'Gestion complète des utilisateurs (élèves, enseignants, personnel)', en: 'Complete user management (students, teachers, staff)', es: 'Gestión completa de usuarios (estudiantes, profesores, personal)', zh: '完整的用户管理（学生、教师、员工）', ja: '完全なユーザー管理（学生、教師、スタッフ）' },
  'admin_task_2': { fr: 'Configuration des paramètres globaux du système', en: 'Configuration of global system settings', es: 'Configuración de los ajustes globales del sistema', zh: '全局系统设置的配置', ja: 'グローバルシステム設定の構成' },
  'admin_task_3': { fr: 'Supervision des présences et résolution des anomalies', en: 'Supervision of attendance and resolution of anomalies', es: 'Supervisión de la asistencia y resolución de anomalías', zh: '出勤监督和异常解决', ja: '出席の監督と異常の解決' },
  'admin_task_4': { fr: 'Génération et analyse des rapports statistiques', en: 'Generation and analysis of statistical reports', es: 'Generación y análisis de informes estadísticos', zh: '统计报告的生成和分析', ja: '統計レポートの生成と分析' },
  'admin_task_5': { fr: 'Gestion des bornes de pointage et de la sécurité biométrique', en: 'Management of clocking terminals and biometric security', es: 'Gestión de terminales de fichaje y seguridad biométrica', zh: '打卡终端和生物识别安全的管理', ja: '打刻端末と生体認証セキュリティの管理' },
  'teacher_desc': { fr: 'En tant qu\'enseignant, vous êtes au cœur du dispositif pédagogique. Vous assurez le suivi de vos classes et la validation des présences.', en: 'As a teacher, you are at the heart of the educational system. You ensure the monitoring of your classes and the validation of attendance.', es: 'Como profesor, estás en el corazón del sistema educativo. Aseguras el seguimiento de tus clases y la validación de la asistencia.', zh: '作为一名教师，您是教育系统的核心。您确保监控您的班级并验证出勤率。', ja: '教師として、あなたは教育システムの中心にいます。クラスの監視と出席の検証を確実にします。' },
  'teacher_task_1': { fr: 'Gestion de l\'appel en classe et validation des présences', en: 'Management of roll call in class and validation of attendance', es: 'Gestión del pase de lista en clase y validación de la asistencia', zh: '课堂点名管理和出勤验证', ja: 'クラスでの点呼管理と出席の検証' },
  'teacher_task_2': { fr: 'Suivi de l\'assiduité des élèves de vos cours', en: 'Monitoring the attendance of students in your courses', es: 'Seguimiento de la asistencia de los estudiantes en sus cursos', zh: '监控您课程中学生的出勤率', ja: 'コース内の学生の出席の監視' },
  'teacher_task_3': { fr: 'Consultation des emplois du temps et des listes de classes', en: 'Consultation of timetables and class lists', es: 'Consulta de horarios y listas de clases', zh: '查阅时间表和班级列表', ja: '時間割とクラスリストの参照' },
  'teacher_task_4': { fr: 'Communication avec l\'administration concernant les absences', en: 'Communication with the administration regarding absences', es: 'Comunicación con la administración sobre las ausencias', zh: '与管理部门沟通缺席事宜', ja: '欠席に関する管理者とのコミュニケーション' },
  'student_role': { fr: 'Élève / Étudiant', en: 'Student', es: 'Estudiante', zh: '学生', ja: '学生' },
  'student_desc': { fr: 'En tant qu\'élève, cette plateforme vous permet de suivre votre assiduité et de valider votre présence aux cours de manière autonome.', en: 'As a student, this platform allows you to track your attendance and validate your presence in classes independently.', es: 'Como estudiante, esta plataforma te permite realizar un seguimiento de tu asistencia y validar tu presencia en las clases de forma independiente.', zh: '作为一名学生，该平台允许您独立跟踪您的出勤情况并验证您在课堂上的出勤情况。', ja: '学生として、このプラットフォームを使用すると、出席を追跡し、クラスへの出席を独自に検証できます。' },
  'student_task_1': { fr: 'Pointage biométrique ou par QR code aux bornes de l\'établissement', en: 'Biometric or QR code clocking at the establishment\'s terminals', es: 'Fichaje biométrico o por código QR en los terminales del establecimiento', zh: '在机构终端进行生物识别或二维码打卡', ja: '施設の端末での生体認証またはQRコード打刻' },
  'student_task_2': { fr: 'Consultation de votre historique de présence et de vos statistiques', en: 'Consultation of your attendance history and statistics', es: 'Consulta de tu historial de asistencia y estadísticas', zh: '查阅您的出勤历史和统计数据', ja: '出席履歴と統計の参照' },
  'student_task_3': { fr: 'Visualisation de votre emploi du temps et de vos classes', en: 'Visualization of your timetable and classes', es: 'Visualización de tu horario y clases', zh: '可视化您的时间表和班级', ja: '時間割とクラスの視覚化' },
  'student_task_4': { fr: 'Justification des absences et retards auprès de l\'administration', en: 'Justification of absences and lateness to the administration', es: 'Justificación de ausencias y retrasos ante la administración', zh: '向管理部门说明缺席和迟到的原因', ja: '管理者への欠席と遅刻の正当化' },
  'admin_staff': { fr: 'Personnel Administratif', en: 'Administrative Staff', es: 'Personal Administrativo', zh: '行政人员', ja: '管理スタッフ' },
  'admin_staff_desc': { fr: 'En tant que membre de l\'administration, vous assurez le suivi quotidien de la vie scolaire et la gestion des flux d\'élèves.', en: 'As a member of the administration, you ensure the daily monitoring of school life and the management of student flows.', es: 'Como miembro de la administración, aseguras el seguimiento diario de la vida escolar y la gestión de los flujos de estudiantes.', zh: '作为管理部门的一员，您确保对学校生活进行日常监控并管理学生流动。', ja: '管理者の一員として、学校生活の日常的な監視と学生の流れの管理を確実にします。' },
  'admin_staff_task_1': { fr: 'Contrôle des accès et supervision des bornes de pointage', en: 'Access control and supervision of clocking terminals', es: 'Control de accesos y supervisión de terminales de fichaje', zh: '访问控制和打卡终端监督', ja: 'アクセス制御と打刻端末の監督' },
  'admin_staff_task_2': { fr: 'Gestion des retards, absences et justifications des élèves', en: 'Management of student lateness, absences and justifications', es: 'Gestión de retrasos, ausencias y justificaciones de los estudiantes', zh: '学生迟到、缺席和请假的管理', ja: '学生の遅刻、欠席、正当化の管理' },
  'admin_staff_task_3': { fr: 'Assistance aux élèves et enseignants sur l\'utilisation du système', en: 'Assistance to students and teachers on the use of the system', es: 'Asistencia a estudiantes y profesores sobre el uso del sistema', zh: '协助学生和教师使用系统', ja: 'システムの使用に関する学生と教師への支援' },
  'admin_staff_task_4': { fr: 'Suivi administratif des dossiers scolaires et édition de rapports', en: 'Administrative follow-up of school records and editing of reports', es: 'Seguimiento administrativo de expedientes escolares y edición de informes', zh: '学校记录的行政跟进和报告编辑', ja: '学校の記録の管理フォローアップとレポートの編集' },

  // Classes
  'unassigned': { fr: 'Non assigné', en: 'Unassigned', es: 'No asignado', zh: '未分配', ja: '未割り当て' },
  'unspecified_level': { fr: 'Niveau non spécifié', en: 'Unspecified level', es: 'Nivel no especificado', zh: '未指定级别', ja: '指定されていないレベル' },
  'new_class': { fr: 'Nouvelle Classe', en: 'New Class', es: 'Nueva Clase', zh: '新班级', ja: '新しいクラス' },
  'edit_class': { fr: 'Modifier la Classe', en: 'Edit Class', es: 'Editar Clase', zh: '编辑班级', ja: 'クラスを編集' },
  'saving': { fr: 'Enregistrement...', en: 'Saving...', es: 'Guardando...', zh: '保存中...', ja: '保存中...' },
  'confirm_delete_class': { fr: 'Êtes-vous sûr de vouloir supprimer cette classe ?', en: 'Are you sure you want to delete this class?', es: '¿Estás seguro de que quieres eliminar esta clase?', zh: '您确定要删除此班级吗？', ja: 'このクラスを削除してもよろしいですか？' },
  'error_saving': { fr: 'Une erreur est survenue.', en: 'An error occurred.', es: 'Ocurrió un error.', zh: '发生错误。', ja: 'エラーが発生しました。' },

  // Reports
  'not_assigned_to_class': { fr: 'Vous n\'êtes assigné à aucune classe en tant que professeur principal. Veuillez contacter un administrateur.', en: 'You are not assigned to any class as a head teacher. Please contact an administrator.', es: 'No está asignado a ninguna clase como profesor principal. Póngase en contacto con un administrador.', zh: '您未被分配为任何班级的班主任。请联系管理员。', ja: '担任としてクラスに割り当てられていません。管理者に連絡してください。' },
  'reports_generated_success': { fr: 'Les rapports ont été générés et mis à jour avec succès !', en: 'Reports have been successfully generated and updated!', es: '¡Los informes se han generado y actualizado con éxito!', zh: '报告已成功生成并更新！', ja: 'レポートが正常に生成され、更新されました！' },
  'error_generating_reports': { fr: 'Une erreur est survenue lors de la génération des rapports: ', en: 'An error occurred while generating reports: ', es: 'Ocurrió un error al generar los informes: ', zh: '生成报告时出错： ', ja: 'レポートの生成中にエラーが発生しました： ' },
  'no_reports_generated': { fr: 'Aucun rapport généré pour le moment.', en: 'No reports generated yet.', es: 'Aún no se han generado informes.', zh: '尚未生成报告。', ja: 'レポートはまだ生成されていません。' },

  // Classroom
  'error_adding_points': { fr: 'Erreur lors de l\'ajout des points', en: 'Error adding points', es: 'Error al agregar puntos', zh: '添加点数时出错', ja: 'ポイントの追加中にエラーが発生しました' },
  'error_adding_resource': { fr: 'Erreur lors de l\'ajout de la ressource', en: 'Error adding resource', es: 'Error al agregar recurso', zh: '添加资源时出错', ja: 'リソースの追加中にエラーが発生しました' },

  // KioskMode
  'qr_read_error': { fr: 'Erreur lors de la lecture du QR Code.', en: 'Error reading QR Code.', es: 'Error al leer el código QR.', zh: '读取二维码时出错。', ja: 'QRコードの読み取り中にエラーが発生しました。' },
  'webauthn_not_supported': { fr: 'WebAuthn non supporté ou annulé, utilisation du fallback:', en: 'WebAuthn not supported or cancelled, using fallback:', es: 'WebAuthn no compatible o cancelado, usando alternativa:', zh: '不支持或已取消 WebAuthn，使用后备方案：', ja: 'WebAuthnがサポートされていないかキャンセルされました。フォールバックを使用します：' },
  'user_not_recognized': { fr: 'Utilisateur non reconnu dans la base de données.', en: 'User not recognized in the database.', es: 'Usuario no reconocido en la base de datos.', zh: '数据库中未识别出用户。', ja: 'データベースでユーザーが認識されません。' },
  'scan_cancelled': { fr: 'Scan annulé ou non reconnu.', en: 'Scan cancelled or not recognized.', es: 'Escaneo cancelado o no reconocido.', zh: '扫描已取消或未识别。', ja: 'スキャンがキャンセルされたか、認識されませんでした。' },
  'back_to_list': { fr: 'Retour à la liste', en: 'Back to list', es: 'Volver a la lista', zh: '返回列表', ja: 'リストに戻る' },
  'start_scan': { fr: 'Lancer le scan', en: 'Start scan', es: 'Iniciar escaneo', zh: '开始扫描', ja: 'スキャンを開始' },

  // IntegrationCode
  'flutter_architecture': { fr: 'Architecture Flutter', en: 'Flutter Architecture', es: 'Arquitectura Flutter', zh: 'Flutter 架构', ja: 'Flutterアーキテクチャ' },
  'firebase_structure': { fr: 'Structure Firebase', en: 'Firebase Structure', es: 'Estructura Firebase', zh: 'Firebase 结构', ja: 'Firebase構造' },
  'flutter_code_attendance': { fr: 'Code Flutter (Présence)', en: 'Flutter Code (Attendance)', es: 'Código Flutter (Asistencia)', zh: 'Flutter 代码（出勤）', ja: 'Flutterコード（出席）' },
  'cloud_functions_reports': { fr: 'Cloud Functions (Rapports)', en: 'Cloud Functions (Reports)', es: 'Cloud Functions (Informes)', zh: '云函数（报告）', ja: 'Cloud Functions（レポート）' },
  'please_scan_fingerprint': { fr: 'Veuillez scanner votre empreinte pour enregistrer votre présence', en: 'Please scan your fingerprint to record your attendance', es: 'Por favor, escanee su huella dactilar para registrar su asistencia', zh: '请扫描您的指纹以记录您的出勤情况', ja: '出席を記録するために指紋をスキャンしてください' },
  'biometric_error': { fr: 'Erreur biométrique', en: 'Biometric error', es: 'Error biométrico', zh: '生物识别错误', ja: '生体認証エラー' },
  'arrival_recorded_success': { fr: 'Arrivée enregistrée avec succès', en: 'Arrival recorded successfully', es: 'Llegada registrada con éxito', zh: '到达记录成功', ja: '到着が正常に記録されました' },
  'departure_recorded_success': { fr: 'Départ enregistré avec succès', en: 'Departure recorded successfully', es: 'Salida registrada con éxito', zh: '离开记录成功', ja: '出発が正常に記録されました' },
  'weekly_reports_generated_success': { fr: 'Rapports hebdomadaires générés avec succès.', en: 'Weekly reports generated successfully.', es: 'Informes semanales generados con éxito.', zh: '每周报告生成成功。', ja: '週次レポートが正常に生成されました。' },

  // Overview
  'overview': { fr: 'Vue d\'ensemble', en: 'Overview', es: 'Visión general', zh: '概览', ja: '概要' },
  'presents': { fr: 'Présents', en: 'Present', es: 'Presentes', zh: '出勤', ja: '出席' },
  'lates': { fr: 'Retards', en: 'Lates', es: 'Tardanzas', zh: '迟到', ja: '遅刻' },
  'absents': { fr: 'Absents', en: 'Absents', es: 'Ausentes', zh: '缺席', ja: '欠席' },
  'attendance_rate': { fr: 'Taux de présence', en: 'Attendance Rate', es: 'Tasa de asistencia', zh: '出勤率', ja: '出席率' },
  'weekly_evolution': { fr: 'Évolution sur la semaine', en: 'Weekly Evolution', es: 'Evolución semanal', zh: '每周演变', ja: '週の推移' },
  'class_distribution': { fr: 'Répartition par classe', en: 'Class Distribution', es: 'Distribución por clase', zh: '班级分布', ja: 'クラス分布' },
  'recent_alerts': { fr: 'Alertes récentes', en: 'Recent Alerts', es: 'Alertas recientes', zh: '最近的警报', ja: '最近のアラート' },

  // Users
  'manage_users': { fr: 'Gérez les élèves, enseignants et le personnel', en: 'Manage students, teachers and staff', es: 'Gestionar estudiantes, profesores y personal', zh: '管理学生、教师和员工', ja: '学生、教師、スタッフの管理' },
  'add_user': { fr: 'Ajouter un utilisateur', en: 'Add user', es: 'Añadir usuario', zh: '添加用户', ja: 'ユーザーを追加' },
  'notify_selection': { fr: 'Notifier la sélection', en: 'Notify selection', es: 'Notificar selección', zh: '通知选择', ja: '選択を通知' },
  'name': { fr: 'Nom', en: 'Name', es: 'Nombre', zh: '姓名', ja: '名前' },
  'firstname': { fr: 'Prénom', en: 'First name', es: 'Nombre', zh: '名字', ja: '名' },
  'class': { fr: 'Classe', en: 'Class', es: 'Clase', zh: '班级', ja: 'クラス' },
  'id_number': { fr: 'Matricule', en: 'ID Number', es: 'Matrícula', zh: '学号', ja: '学籍番号' },
  'actions': { fr: 'Actions', en: 'Actions', es: 'Acciones', zh: '操作', ja: 'アクション' },
  'all': { fr: 'Tous', en: 'All', es: 'Todos', zh: '全部', ja: 'すべて' },
  'house': { fr: 'Maison', en: 'House', es: 'Casa', zh: '学院', ja: 'ハウス' },
  'biometrics': { fr: 'Biométrie', en: 'Biometrics', es: 'Biometría', zh: '生物识别', ja: '生体認証' },
  'registered': { fr: 'Enregistré', en: 'Registered', es: 'Registrado', zh: '已注册', ja: '登録済み' },
  'missing': { fr: 'Manquant', en: 'Missing', es: 'Falta', zh: '缺失', ja: '不足' },
  'view_details': { fr: 'Voir les détails', en: 'View details', es: 'Ver detalles', zh: '查看详情', ja: '詳細を見る' },
  'user_details': { fr: 'Détails de l\'utilisateur', en: 'User details', es: 'Detalles del usuario', zh: '用户详情', ja: 'ユーザーの詳細' },
  'not_defined': { fr: 'Non défini', en: 'Not defined', es: 'No definido', zh: '未定义', ja: '未定義' },
  'registration_date': { fr: 'Date d\'inscription', en: 'Registration date', es: 'Fecha de registro', zh: '注册日期', ja: '登録日' },
  'unknown': { fr: 'Inconnu', en: 'Unknown', es: 'Desconocido', zh: '未知', ja: '不明' },
  'biometric_status': { fr: 'Statut biométrique', en: 'Biometric status', es: 'Estado biométrico', zh: '生物识别状态', ja: '生体認証ステータス' },
  'registration_complete': { fr: 'Enregistrement complet', en: 'Registration complete', es: 'Registro completo', zh: '注册完成', ja: '登録完了' },
  'registration_incomplete': { fr: 'Enregistrement incomplet', en: 'Registration incomplete', es: 'Registro incompleto', zh: '注册未完成', ja: '登録未完了' },
  'close': { fr: 'Fermer', en: 'Close', es: 'Cerrar', zh: '关闭', ja: '閉じる' },
  'edit_user': { fr: 'Modifier l\'utilisateur', en: 'Edit user', es: 'Editar usuario', zh: '编辑用户', ja: 'ユーザーを編集' },
  'loading_users': { fr: 'Chargement des utilisateurs...', en: 'Loading users...', es: 'Cargando usuarios...', zh: '加载用户中...', ja: 'ユーザーを読み込んでいます...' },
  'no_users_found': { fr: 'Aucun utilisateur trouvé.', en: 'No users found.', es: 'No se encontraron usuarios.', zh: '未找到用户。', ja: 'ユーザーが見つかりません。' },
  'configure_firebase': { fr: 'Veuillez configurer Firebase.', en: 'Please configure Firebase.', es: 'Por favor configure Firebase.', zh: '请配置Firebase。', ja: 'Firebaseを設定してください。' },
  'save': { fr: 'Enregistrer', en: 'Save', es: 'Guardar', zh: '保存', ja: '保存' },
  'delete_user_confirm': { fr: 'Supprimer l\'utilisateur ?', en: 'Delete user?', es: '¿Eliminar usuario?', zh: '删除用户？', ja: 'ユーザーを削除しますか？' },
  'delete_user_warning': { fr: 'Êtes-vous sûr de vouloir supprimer', en: 'Are you sure you want to delete', es: '¿Estás seguro de que quieres eliminar a', zh: '您确定要删除', ja: '本当に削除しますか' },
  'send_notification': { fr: 'Envoyer une notification', en: 'Send a notification', es: 'Enviar una notificación', zh: '发送通知', ja: '通知を送信' },
  'notification_target_info': { fr: 'Cette notification sera envoyée à {count} utilisateur(s) correspondant à vos filtres actuels.', en: 'This notification will be sent to {count} user(s) matching your current filters.', es: 'Esta notificación se enviará a {count} usuario(s) que coinciden con sus filtros actuales.', zh: '此通知将发送给符合您当前过滤条件的 {count} 个用户。', ja: 'この通知は、現在のフィルターに一致する {count} 人のユーザーに送信されます。' },
  'notification_title_placeholder': { fr: 'Titre de la notification', en: 'Notification title', es: 'Título de la notificación', zh: '通知标题', ja: '通知タイトル' },
  'message': { fr: 'Message', en: 'Message', es: 'Mensaje', zh: '消息', ja: 'メッセージ' },
  'notification_message_placeholder': { fr: 'Contenu de votre message...', en: 'Content of your message...', es: 'Contenido de su mensaje...', zh: '您的消息内容...', ja: 'メッセージの内容...' },
  'type': { fr: 'Type', en: 'Type', es: 'Tipo', zh: '类型', ja: 'タイプ' },
  'info': { fr: 'Information', en: 'Information', es: 'Información', zh: '信息', ja: '情報' },
  'warning': { fr: 'Avertissement', en: 'Warning', es: 'Advertencia', zh: '警告', ja: '警告' },
  'success': { fr: 'Succès', en: 'Success', es: 'Éxito', zh: '成功', ja: '成功' },
  'send': { fr: 'Envoyer', en: 'Send', es: 'Enviar', zh: '发送', ja: '送信' },

  // Connections
  'recent_connections_desc': { fr: 'Historique des dernières connexions', en: 'History of last connections', es: 'Historial de las últimas conexiones', zh: '最近连接历史', ja: '最近の接続履歴' },
  'contact': { fr: 'Contact', en: 'Contact', es: 'Contacto', zh: '联系方式', ja: '連絡先' },
  'datetime': { fr: 'Date & Heure', en: 'Date & Time', es: 'Fecha y Hora', zh: '日期和时间', ja: '日時' },
  'no_connections': { fr: 'Aucune connexion récente.', en: 'No recent connections.', es: 'No hay conexiones recientes.', zh: '没有最近的连接。', ja: '最近の接続はありません。' },

  // Sidebar Categories
  'main_category': { fr: 'Principal', en: 'Main', es: 'Principal', zh: '主要', ja: 'メイン' },
  'schooling_category': { fr: 'Scolarité', en: 'Schooling', es: 'Escolaridad', zh: '学校教育', ja: '学校教育' },
  'student_life_category': { fr: 'Vie Étudiante', en: 'Student Life', es: 'Vida Estudiantil', zh: '学生生活', ja: '学生生活' },
  'administration_category': { fr: 'Administration', en: 'Administration', es: 'Administración', zh: '管理', ja: '管理' },

  // Install Guide
  'install_app_title': { fr: 'Installer l\'application', en: 'Install the application', es: 'Instalar la aplicación', zh: '安装应用程序', ja: 'アプリをインストールする' },
  'install_app_desc': { fr: 'Pour installer l\'application sur votre appareil :', en: 'To install the application on your device:', es: 'Para instalar la aplicación en su dispositivo:', zh: '要在您的设备上安装该应用程序：', ja: 'デバイスにアプリをインストールするには：' },
  'install_ios': { fr: 'Sur iPhone / iPad (Safari) :', en: 'On iPhone / iPad (Safari):', es: 'En iPhone / iPad (Safari):', zh: '在 iPhone / iPad (Safari) 上：', ja: 'iPhone / iPad (Safari) の場合：' },
  'install_ios_step1': { fr: 'Appuyez sur l\'icône Partager en bas de l\'écran.', en: 'Tap the Share icon at the bottom of the screen.', es: 'Toca el icono Compartir en la parte inferior de la pantalla.', zh: '点击屏幕底部的分享图标。', ja: '画面下部の共有アイコンをタップします。' },
  'install_ios_step2': { fr: 'Faites défiler vers le bas et sélectionnez Sur l\'écran d\'accueil.', en: 'Scroll down and select Add to Home Screen.', es: 'Desplázate hacia abajo y selecciona Añadir a la pantalla de inicio.', zh: '向下滚动并选择添加到主屏幕。', ja: '下にスクロールして「ホーム画面に追加」を選択します。' },
  'install_ios_step3': { fr: 'Appuyez sur Ajouter en haut à droite.', en: 'Tap Add in the top right.', es: 'Toca Añadir en la parte superior derecha.', zh: '点击右上角的添加。', ja: '右上の「追加」をタップします。' },
  'install_android': { fr: 'Sur Android (Chrome) :', en: 'On Android (Chrome):', es: 'En Android (Chrome):', zh: '在 Android (Chrome) 上：', ja: 'Android (Chrome) の場合：' },
  'install_android_step1': { fr: 'Appuyez sur le menu (trois points) en haut à droite.', en: 'Tap the menu (three dots) in the top right.', es: 'Toca el menú (tres puntos) en la parte superior derecha.', zh: '点击右上角的菜单（三个点）。', ja: '右上のメニュー（3つのドット）をタップします。' },
  'install_android_step2': { fr: 'Sélectionnez Ajouter à l\'écran d\'accueil ou Installer l\'application.', en: 'Select Add to Home Screen or Install app.', es: 'Selecciona Añadir a la pantalla de inicio o Instalar aplicación.', zh: '选择添加到主屏幕或安装应用程序。', ja: '「ホーム画面に追加」または「アプリをインストール」を選択します。' },
  'got_it': { fr: 'J\'ai compris', en: 'Got it', es: 'Entendido', zh: '知道了', ja: 'わかりました' },

  // Header
  'no_results_found': { fr: 'Aucun résultat trouvé', en: 'No results found', es: 'No se encontraron resultados', zh: '未找到结果', ja: '結果が見つかりません' },

  // Houses
  'houses_system': { fr: 'Système des Maisons', en: 'Houses System', es: 'Sistema de Casas', zh: '学院系统', ja: 'ハウスシステム' },
  'ranking': { fr: 'Classement', en: 'Ranking', es: 'Clasificación', zh: '排名', ja: 'ランキング' },
  'assign_points': { fr: 'Attribuer des points', en: 'Assign points', es: 'Asignar puntos', zh: '分配点数', ja: 'ポイントを割り当てる' },
  'system_poster': { fr: 'Affiche du Système', en: 'System Poster', es: 'Póster del Sistema', zh: '系统海报', ja: 'システムポスター' },
  'houses_management': { fr: 'Gestion des Maisons', en: 'Houses Management', es: 'Gestión de Casas', zh: '学院管理', ja: 'ハウス管理' },
  'resp': { fr: 'Resp:', en: 'Mgr:', es: 'Resp:', zh: '负责人:', ja: '責任者:' },
  'pts': { fr: 'pts', en: 'pts', es: 'pts', zh: '分', ja: 'ポイント' },
  'position': { fr: 'Position', en: 'Position', es: 'Posición', zh: '位置', ja: '順位' },
  'points': { fr: 'Points', en: 'Points', es: 'Puntos', zh: '点数', ja: 'ポイント' },
  'select_student': { fr: 'Sélectionner un élève...', en: 'Select a student...', es: 'Seleccionar un estudiante...', zh: '选择一名学生...', ja: '学生を選択...' },
  'action_type': { fr: 'Type d\'action', en: 'Action type', es: 'Tipo de acción', zh: '操作类型', ja: 'アクションタイプ' },
  'reward_gain': { fr: 'Récompenser (Gain)', en: 'Reward (Gain)', es: 'Recompensar (Ganancia)', zh: '奖励 (获得)', ja: '報酬 (獲得)' },
  'sanction_penalty': { fr: 'Sanctionner (Pénalité)', en: 'Sanction (Penalty)', es: 'Sancionar (Penalización)', zh: '制裁 (惩罚)', ja: '制裁 (ペナルティ)' },
  'reason': { fr: 'Raison', en: 'Reason', es: 'Razón', zh: '原因', ja: '理由' },
  'other_custom': { fr: 'Autre (Personnalisé)', en: 'Other (Custom)', es: 'Otro (Personalizado)', zh: '其他 (自定义)', ja: 'その他 (カスタム)' },
  'custom_reason': { fr: 'Raison personnalisée...', en: 'Custom reason...', es: 'Razón personalizada...', zh: '自定义原因...', ja: 'カスタム理由...' },
  'save_points': { fr: 'Enregistrer les points', en: 'Save points', es: 'Guardar puntos', zh: '保存点数', ja: 'ポイントを保存' },
  'no_points_history': { fr: 'Aucun historique de points disponible.', en: 'No points history available.', es: 'No hay historial de puntos disponible.', zh: '没有可用的点数历史记录。', ja: 'ポイント履歴はありません。' },
  'unknown_student': { fr: 'Élève inconnu', en: 'Unknown student', es: 'Estudiante desconocido', zh: '未知学生', ja: '不明な学生' },
  'school_name': { fr: 'École Internationale du Centre Pédagogique', en: 'International School of the Pedagogical Center', es: 'Escuela Internacional del Centro Pedagógico', zh: '教学中心国际学校', ja: '教育センターインターナショナルスクール' },
  'school_house': { fr: 'Maison de l\'école', en: 'School house', es: 'Casa de la escuela', zh: '学校学院', ja: 'スクールハウス' },
  'points_attribution': { fr: 'Attribution des Points', en: 'Points Attribution', es: 'Atribución de Puntos', zh: '点数分配', ja: 'ポイントの割り当て' },
  'school_uniform': { fr: 'Tenue Scolaire', en: 'School Uniform', es: 'Uniforme Escolar', zh: '校服', ja: '制服' },
  'complete_clean_uniform': { fr: 'Tenue complète et propre', en: 'Complete and clean uniform', es: 'Uniforme completo y limpio', zh: '校服完整且干净', ja: '完全で清潔な制服' },
  'clean_shoes': { fr: 'Chaussures propres', en: 'Clean shoes', es: 'Zapatos limpios', zh: '鞋子干净', ja: '清潔な靴' },
  'discipline': { fr: 'Discipline', en: 'Discipline', es: 'Disciplina', zh: '纪律', ja: '規律' },
  'respect_teachers': { fr: 'Respect des enseignants', en: 'Respect for teachers', es: 'Respeto a los profesores', zh: '尊重教师', ja: '教師への敬意' },
  'silence_in_class': { fr: 'Silence en classe', en: 'Silence in class', es: 'Silencio en clase', zh: '课堂安静', ja: '授業中の静けさ' },
  'behavior': { fr: 'Comportement', en: 'Behavior', es: 'Comportamiento', zh: '行为', ja: '行动' },
  'help_classmate': { fr: 'Aide à un camarade', en: 'Helping a classmate', es: 'Ayuda a un compañero', zh: '帮助同学', ja: 'クラスメイトを助ける' },
  'respect_rules': { fr: 'Respect des règles', en: 'Respect for rules', es: 'Respeto a las reglas', zh: '遵守规则', ja: 'ルールの遵守' },
  'participation': { fr: 'Participation', en: 'Participation', es: 'Participación', zh: '参与', ja: '参加' },
  'class_participation': { fr: 'Participation en classe', en: 'Class participation', es: 'Participación en clase', zh: '课堂参与', ja: '授業への参加' },
  'activities_sport_culture': { fr: 'Activités (sport/culture)', en: 'Activities (sport/culture)', es: 'Actividades (deporte/cultura)', zh: '活动（体育/文化）', ja: '活動（スポーツ/文化）' },
  'rewards': { fr: 'Récompenses', en: 'Rewards', es: 'Recompensas', zh: '奖励', ja: '報酬' },
  'weekly': { fr: 'Hebdo', en: 'Weekly', es: 'Semanal', zh: '每周', ja: '毎週' },
  'flag_raised': { fr: 'Drapeau hissé', en: 'Flag raised', es: 'Bandera izada', zh: '升旗', ja: '旗の掲揚' },
  'monthly': { fr: 'Mensuel', en: 'Monthly', es: 'Mensual', zh: '每月', ja: '毎月' },
  'month_trophy': { fr: 'Trophée du mois', en: 'Trophy of the month', es: 'Trofeo del mes', zh: '本月奖杯', ja: '今月のトロフィー' },
  'yearly': { fr: 'Annuel', en: 'Yearly', es: 'Anual', zh: '每年', ja: '毎年' },
  'school_cup': { fr: 'Coupe de l\'école', en: 'School cup', es: 'Copa de la escuela', zh: '学校奖杯', ja: 'スクールカップ' },
  'possible_penalties': { fr: 'Pénalités Possibles', en: 'Possible Penalties', es: 'Posibles Penalizaciones', zh: '可能的惩罚', ja: '考えられるペナルティ' },
  'incorrect_uniform': { fr: 'Tenue incorrecte', en: 'Incorrect uniform', es: 'Uniforme incorrecto', zh: '校服不正确', ja: '不適切な制服' },
  'lateness': { fr: 'Retard', en: 'Lateness', es: 'Retraso', zh: '迟到', ja: '遅刻' },
  'lack_of_respect': { fr: 'Manque de respect', en: 'Lack of respect', es: 'Falta de respeto', zh: '缺乏尊重', ja: '敬意の欠如' },
  'rules': { fr: 'Règlement', en: 'Rules', es: 'Reglamento', zh: '规则', ja: 'ルール' },
  'rule_1': { fr: 'Chaque élève appartient à une maison pour toute l\'année scolaire.', en: 'Each student belongs to a house for the entire school year.', es: 'Cada estudiante pertenece a una casa durante todo el año escolar.', zh: '每个学生在整个学年都属于一个学院。', ja: '各学生は1年間ハウスに所属します。' },
  'rule_2': { fr: 'Les points sont cumulatifs pour la maison.', en: 'Points are cumulative for the house.', es: 'Los puntos son acumulativos para la casa.', zh: '点数是学院累计的。', ja: 'ポイントはハウスに蓄積されます。' },
  'rule_3': { fr: 'Seuls les enseignants et la direction peuvent attribuer ou retirer des points.', en: 'Only teachers and management can award or deduct points.', es: 'Solo los profesores y la dirección pueden otorgar o deducir puntos.', zh: '只有教师和管理层才能奖励或扣除点数。', ja: '教師と管理層のみがポイントを付与または減点できます。' },
  'winning_house_msg': { fr: 'La maison qui a le plus de points gagne la Coupe de l\'école !', en: 'The house with the most points wins the School Cup!', es: '¡La casa con más puntos gana la Copa de la Escuela!', zh: '点数最多的学院赢得学校奖杯！', ja: '最もポイントが多いハウスがスクールカップを獲得します！' },
  'add_house': { fr: 'Ajouter une maison', en: 'Add a house', es: 'Añadir una casa', zh: '添加学院', ja: 'ハウスを追加' },
  'color': { fr: 'Couleur', en: 'Color', es: 'Color', zh: '颜色', ja: '色' },
  'edit_house': { fr: 'Modifier la maison', en: 'Edit house', es: 'Editar casa', zh: '编辑学院', ja: 'ハウスを編集' },
  'new_house': { fr: 'Nouvelle maison', en: 'New house', es: 'Nueva casa', zh: '新学院', ja: '新しいハウス' },
  'choose_icon': { fr: '1. Choisir une icône', en: '1. Choose an icon', es: '1. Elegir un icono', zh: '1. 选择一个图标', ja: '1. アイコンを選択' },
  'house_info': { fr: '2. Informations de la maison', en: '2. House information', es: '2. Información de la casa', zh: '2. 学院信息', ja: '2. ハウス情報' },
  'house_name': { fr: 'Nom de la maison', en: 'House name', es: 'Nombre de la casa', zh: '学院名称', ja: 'ハウス名' },
  'animal': { fr: 'Animal', en: 'Animal', es: 'Animal', zh: '动物', ja: '動物' },
  'values': { fr: 'Valeurs', en: 'Values', es: 'Valores', zh: '价值观', ja: '価値観' },
  'initial_points': { fr: 'Points initiaux', en: 'Initial points', es: 'Puntos iniciales', zh: '初始点数', ja: '初期ポイント' },
  'manager': { fr: 'Responsable', en: 'Manager', es: 'Responsable', zh: '负责人', ja: '責任者' },
  'none': { fr: 'Aucun', en: 'None', es: 'Ninguno', zh: '无', ja: 'なし' },
  'house_description_placeholder': { fr: 'Description de la maison...', en: 'House description...', es: 'Descripción de la casa...', zh: '学院描述...', ja: 'ハウスの説明...' },
  'confirm_delete': { fr: 'Confirmer la suppression', en: 'Confirm deletion', es: 'Confirmar eliminación', zh: '确认删除', ja: '削除の確認' },
  'delete_house_confirm_msg': { fr: 'Êtes-vous sûr de vouloir supprimer cette maison ? Cette action est irréversible.', en: 'Are you sure you want to delete this house? This action is irreversible.', es: '¿Estás seguro de que quieres eliminar esta casa? Esta acción es irreversible.', zh: '您确定要删除这个学院吗？此操作不可逆。', ja: '本当にこのハウスを削除しますか？この操作は元に戻せません。' },
  'student_no_house_alert': { fr: 'Cet élève n\'est assigné à aucune maison.', en: 'This student is not assigned to any house.', es: 'Este estudiante no está asignado a ninguna casa.', zh: '该学生未分配到任何学院。', ja: 'この学生はどのハウスにも割り当てられていません。' },
  'select_rule_reason_alert': { fr: 'Veuillez sélectionner une règle ou saisir une raison.', en: 'Please select a rule or enter a reason.', es: 'Por favor, seleccione una regla o introduzca un motivo.', zh: '请选择一条规则或输入原因。', ja: 'ルールを選択するか、理由を入力してください。' },
  'house_points_won': { fr: 'Points de Maison gagnés !', en: 'House Points won!', es: '¡Puntos de Casa ganados!', zh: '获得学院点数！', ja: 'ハウスポイントを獲得しました！' },
  'house_points_lost': { fr: 'Points de Maison perdus', en: 'House Points lost', es: 'Puntos de Casa perdidos', zh: '失去学院点数', ja: 'ハウスポイントを失いました' },
  'points_for_house': { fr: 'points pour la maison', en: 'points for house', es: 'puntos para la casa', zh: '点数给学院', ja: 'ハウスのポイント' },
  'points_assigned_success': { fr: 'Points attribués avec succès !', en: 'Points assigned successfully!', es: '¡Puntos asignados con éxito!', zh: '点数分配成功！', ja: 'ポイントが正常に割り当てられました！' },
  'error_assigning_points': { fr: 'Erreur lors de l\'attribution des points.', en: 'Error assigning points.', es: 'Error al asignar puntos.', zh: '分配点数时出错。', ja: 'ポイントの割り当て中にエラーが発生しました。' },
  'error_saving_house': { fr: 'Erreur lors de l\'enregistrement de la maison.', en: 'Error saving house.', es: 'Error al guardar la casa.', zh: '保存学院时出错。', ja: 'ハウスの保存中にエラーが発生しました。' },
  'error_deleting': { fr: 'Erreur lors de la suppression.', en: 'Error deleting.', es: 'Error al eliminar.', zh: '删除时出错。', ja: '削除中にエラーが発生しました。' },
  'no_manager': { fr: 'Aucun responsable', en: 'No manager', es: 'Sin responsable', zh: '无负责人', ja: '責任者なし' },
  'current_ranking': { fr: 'Classement Actuel', en: 'Current Ranking', es: 'Clasificación Actual', zh: '当前排名', ja: '現在のランキング' },

  // Calendar
  'calendar': { fr: 'Calendrier', en: 'Calendar', es: 'Calendario', zh: '日历', ja: 'カレンダー' },
  'events': { fr: 'Événements', en: 'Events', es: 'Eventos', zh: '事件', ja: 'イベント' },
  'create_event': { fr: 'Créer un événement', en: 'Create an event', es: 'Crear un evento', zh: '创建事件', ja: 'イベントを作成' },
  'event_title': { fr: 'Titre de l\'événement', en: 'Event title', es: 'Título del evento', zh: '事件标题', ja: 'イベントのタイトル' },
  'event_description': { fr: 'Description', en: 'Description', es: 'Descripción', zh: '描述', ja: '説明' },
  'event_date': { fr: 'Date', en: 'Date', es: 'Fecha', zh: '日期', ja: '日付' },
  'event_time': { fr: 'Heure', en: 'Time', es: 'Hora', zh: '时间', ja: '時間' },
  'event_type': { fr: 'Type d\'événement', en: 'Event type', es: 'Tipo de evento', zh: '事件类型', ja: 'イベントタイプ' },
  'event_audience': { fr: 'Audience', en: 'Audience', es: 'Audiencia', zh: '受众', ja: '対象者' },
  'event_publisher': { fr: 'Publié par', en: 'Published by', es: 'Publicado por', zh: '发布者', ja: '公開者' },
  'event_meeting': { fr: 'Réunion', en: 'Meeting', es: 'Reunión', zh: '会议', ja: '会議' },
  'event_activity': { fr: 'Activité', en: 'Activity', es: 'Actividad', zh: '活动', ja: '活動' },
  'event_exam': { fr: 'Examen', en: 'Exam', es: 'Examen', zh: '考试', ja: '試験' },
  'event_other': { fr: 'Autre', en: 'Other', es: 'Otro', zh: '其他', ja: 'その他' },
  'audience_all': { fr: 'Tous', en: 'All', es: 'Todos', zh: '全部', ja: 'すべて' },
  'audience_teachers': { fr: 'Enseignants', en: 'Teachers', es: 'Profesores', zh: '教师', ja: '教師' },
  'audience_parents': { fr: 'Parents', en: 'Parents', es: 'Padres', zh: '父母', ja: '保護者' },
  'audience_students': { fr: 'Élèves', en: 'Students', es: 'Estudiantes', zh: '学生', ja: '学生' },
  'sync_calendar': { fr: 'Synchroniser', en: 'Sync', es: 'Sincronizar', zh: '同步', ja: '同期' },
  'view_list': { fr: 'Vue Liste', en: 'List View', es: 'Vista de lista', zh: '列表视图', ja: 'リストビュー' },
  'view_calendar': { fr: 'Vue Calendrier', en: 'Calendar View', es: 'Vista de calendario', zh: '日历视图', ja: 'カレンダービュー' },
  'day': { fr: 'Jour', en: 'Day', es: 'Día', zh: '日', ja: '日' },
  'week': { fr: 'Semaine', en: 'Week', es: 'Semana', zh: '周', ja: '週' },
  'month': { fr: 'Mois', en: 'Month', es: 'Mes', zh: '月', ja: '月' },
  'edit_event': { fr: 'Modifier l\'événement', en: 'Edit event', es: 'Editar evento', zh: '编辑事件', ja: 'イベントを編集' },
  'delete_event': { fr: 'Supprimer l\'événement', en: 'Delete event', es: 'Eliminar evento', zh: '删除事件', ja: 'イベントを削除' },
  'event_image_file': { fr: 'Image / Fichier joint', en: 'Image / Attached file', es: 'Imagen / Archivo adjunto', zh: '图片/附件', ja: '画像/添付ファイル' },
  'no_events': { fr: 'Aucun événement', en: 'No events', es: 'No hay eventos', zh: '没有事件', ja: 'イベントなし' },
  'event_created_success': { fr: 'Événement créé avec succès', en: 'Event successfully created', es: 'Evento creado con éxito', zh: '事件创建成功', ja: 'イベントが正常に作成されました' },
  'event_updated_success': { fr: 'Événement modifié avec succès', en: 'Event successfully updated', es: 'Evento actualizado con éxito', zh: '事件更新成功', ja: 'イベントが正常に更新されました' },
  'event_deleted_success': { fr: 'Événement supprimé avec succès', en: 'Event successfully deleted', es: 'Evento eliminado con éxito', zh: '事件删除成功', ja: 'イベントが正常に削除されました' },
  'event_sync_success': { fr: 'Calendrier synchronisé avec succès', en: 'Calendar successfully synced', es: 'Calendario sincronizado con éxito', zh: '日历同步成功', ja: 'カレンダーが正常に同期されました' },
  'event_sync_error': { fr: 'Erreur lors de la synchronisation', en: 'Error during sync', es: 'Error durante la sincronización', zh: '同步期间出错', ja: '同期中にエラーが発生しました' },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  tData: (value: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved as Language) || 'fr';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
  }, [language]);

  const t = (key: string) => {
    return translations[key]?.[language] || key;
  };

  const tData = (value: string) => {
    if (!value) return value;
    const keyMap: Record<string, string> = {
      'admin': 'role_admin',
      'enseignant': 'role_enseignant',
      'élève': 'role_élève',
      'personnel administratif': 'role_personnel administratif',
      'Présent': 'status_Présent',
      'Retard': 'status_Retard',
      'Absent': 'status_Absent',
      'Lun': 'day_Lun',
      'Mar': 'day_Mar',
      'Mer': 'day_Mer',
      'Jeu': 'day_Jeu',
      'Ven': 'day_Ven',
    };
    const key = keyMap[value];
    return key ? t(key) : value;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tData }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
